name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java (if applicable)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y maven
          mvn clean install
      - name: Install Tomcat
        run: |
          sudo apt update
          wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz -O /tmp/tomcat.tar.gz
          sudo mkdir -p /opt/tomcat
          sudo tar -xvzf /tmp/tomcat.tar.gz -C /opt/tomcat --strip-components=1
          sudo chmod -R 755 /opt/tomcat
          sudo sh /opt/tomcat/bin/startup.sh
          echo "Tomcat successfully installed and started."

  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.yml deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
